CREATE DATABASE IF NOT EXISTS sikumbang;
CREATE TABLE IF NOT EXISTS sikumbang_tapera (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_lokasi VARCHAR(100),
    nama_perumahan VARCHAR(255),
    alamat TEXT,
    telpon VARCHAR(100),
    email VARCHAR(255),
    website VARCHAR(255),
    provinsi VARCHAR(255),
    kabupaten VARCHAR(255),
    kecamatan VARCHAR(255),
    koordinat VARCHAR(255),
    pengembang VARCHAR(255),
    jumlah_unit_subsidi INT,
    jumlah_unit_subsidi_terjual INT,
    jumlah_unit_komersil INT,
    jumlah_unit_komersil_terjual INT,
    id_rumah VARCHAR(100),
    blok VARCHAR(100),
    nomor_rumah VARCHAR(100),
    tipe_bangunan VARCHAR(100),
    status_unit VARCHAR(100),
    npwp_MK VARCHAR(100),
    nik_pemilik VARCHAR(100),
    nik_booking VARCHAR(100),
    tanggal_terjual DATE,
    nama_tipe VARCHAR(255),
    harga BIGINT,
    luas_bangunan DECIMAL(10,2),
    luas_lahan DECIMAL(10,2),
    kamar_tidur INT,
    kamar_mandi INT,
    atap TEXT,
    dinding TEXT,
    lantai TEXT,
    pondasi TEXT,
    createdAt DATE,
    updatedAt DATE,
    tahun YEAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_id_lokasi (id_lokasi),
    INDEX idx_id_rumah (id_rumah),
    INDEX idx_provinsi (provinsi),
    INDEX idx_kabupaten (kabupaten),
    INDEX idx_kecamatan (kecamatan),
    INDEX idx_tahun (tahun)
);