CREATE DATABASE IF NOT EXISTS sikumbang;
CREATE TABLE IF NOT EXISTS rumah (
    id VARCHAR(255) PRIMARY KEY,
    id_rumah BIGINT,
    status_rumah VARCHAR(100),
    nama_rumah VARCHAR(255),
    harga_rumah DOUBLE,
    jml_kamar_tidur INT,
    jml_kamar_mandi INT,
    jml_lantai INT,
    luas_tanah DOUBLE,
    luas_bangunan DOUBLE,
    spek_atap TEXT,
    spek_dinding TEXT,
    spek_lantai TEXT,
    spek_pondasi TEXT,
    foto_tampak TEXT,
    foto_denah TEXT,
    id_perumahan VARCHAR(255),
    nama_perumahan VARCHAR(255),
    jenis_perumahan VARCHAR(100),
    jumlah_unit_subsidi INT,
    jumlah_unit_komersil INT,
    longitude DOUBLE,
    latitude DOUBLE,
    kode_wilayah VARCHAR(100),
    nama_wilayah VARCHAR(255),
    nama_provinsi VARCHAR(255),
    nama_kabupaten VARCHAR(255),
    nama_kecamatan VARCHAR(255),
    nama_kelurahan VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);